version: "3.8"
services:
    web:
        build: .
        ports:
            - "8081:8080"
        links:
            - postgres
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always
        expose:
            - "5432"
        environment:
            POSTGRES_PASSWORD: password
    pgadmin:
        image: fenglc/pgadmin4
        restart: always
        ports:
            - "5050:5050"
        links:
            - postgres
        environment:
            - DEFAULT_USER=postgres@example.com
            - DEFAULT_PASSWORD=password
    prometheus:
        image: prom/prometheus
        restart: always
        ports:
            - "9090:9090"
        links:
            - web
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - web
    # TODO: Grafana configuration
    grafana:
        image: grafana/grafana
        restart: always
        ports:
            - "3000:3000"
        links:
            - prometheus
        depends_on:
            - prometheus
